### PR TITLE
parse generate tokens now

### PR DESCRIPTION
**Pull request by mreinstein**
@meryn I've taken removed lib/ from .gitignore. I the lib directory isn't present and containing the source code for the module, anyone pointing at a  github repo in their package.json will have a non-functioning library. (e.g., I'm using my fork of render and parse because the version in npm doesnt support tokens yet. Because lib/ was in my .gitignore,and because I'm referencing my github repo in package.json, it breaks.)

### CODE REVIEW

**Comment by myrne** [comment]
Great, I see tests.

**Comment by myrne** [comment]
Nice job on the readme!

**Comment by myrne** [comment]
Added you as an author. Published as 0.2.0!

**Comment by mreinstein** [comment]
nice! I'll kill my fork and point back at your npm package

**Pull request merged**
